### PR TITLE
fix: don't use ts-node for running tests

### PR DESCRIPTION
**Pull request by gmaclennan**
This stops using ts-node for running tests.

This is because ts-node causes a significant overhead for worker_threads (they take >6s to spawn on my machine, vs. ~5ms without ts-node) and is also a potential source of flakey tests with the work hanging.

The `npm test` script now builds the code first before running tests on the `dist` folder, so the same code that ships to users is being tested.

BREAKING: There is no longer a default export - you now need `const { createServer } = require('mapeo-map-server')`. This is so that other helper modules can be exported (this avoids reaching into the module folder structure and hard-coding paths in the tests). I'm open to reverting this and changing how these are imported in tests.

TODO:
- [ ] convert unit tests to JS
- [ ] add some missing JSDoc types to app.test.js if we want it to be type-checked

### CODE REVIEW

**Comment by achou11** [comment]
> BREAKING: There is no longer a default export - you now need const { createServer } = require('mapeo-map-server'). This is so that other helper modules can be exported (this avoids reaching into the module folder structure and hard-coding paths in the tests). I'm open to reverting this and changing how these are imported in tests.

think i'd rather use hardcoded and somewhat inconvenient paths rather than exposing unnecessary exports in the entry file - just thinking from a publishing standpoint. unless we think there are some exports that would be useful to expose to the end user?

**Comment by gmaclennan** [comment]
@achou11 I just force-pushed here and did some further cleanup:

- Reverted to single export of main module (createServer)
- Only run mock server during tests where it is needed
- Remove unnecessary validation of fixtures (tests already validate these fixtures)

Planning to split up the e2e tests by route, since the file is getting hard to manage.
I'm also considering moving from msw to [nock](https://github.com/nock/nock) because it looks like msw has chosen to only support Node 16, and the failure of headers being passed through is not great.

**Comment by gmaclennan** [comment]
I split the e2e tests into separate files, and created an eventSource helper since we use that a lot. I have been finding having so many tests in a single file really hard to navigate.
Ready for merge now in my opinion, then I can rebase the SSE work on master.

**Comment by gmaclennan** [comment]
NB: I am skipping the SSE import error test for now, I think we should create the error by passing a malformed mbtiles file rather than the closing of the server we are doing now (which ideally would not create an error, but rather wait for the import to complete).

**Review by achou11 — APPROVED** [review]
lgtm! also fine with switching to nock for the mock server if it helps with issues you've encountered

**Pull request merged**
